basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    basic.pause(100)
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(100)
    basic.showIcon(IconNames.Giraffe)
    basic.pause(100)
    basic.showIcon(IconNames.Scissors)
    basic.showString("\"GARCIA DANNA\"")
})
